version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pedantic2-app
    ports:
      - "3000:3000"
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - workflow_files:/tmp/workflow_files
      - workflow_dbs:/tmp/workflow_dbs
    restart: unless-stopped

volumes:
  workflow_files:
  workflow_dbs:


